-- AlterTable
ALTER TABLE "population" ALTER COLUMN "population" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_of_children_under_the_age_of_1" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_of_children_under_the_age_of_5" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_of_children_under_the_age_of_15" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_under_the_age_of_25" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_15_to_64_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_older_than_15_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_older_than_18_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_at_age_1" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_1_to_4_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_5_to_9_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_10_to_14_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_15_to_19_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_20_to_29_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_30_to_39_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_40_to_49_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_50_to_59_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_60_to_69_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_70_to_79_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_80_to_89_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_aged_90_to_99_years" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "population_older_than_100_years" SET DATA TYPE DECIMAL(65,30);
